function init(self)
	self.on = false
end

local function get_animation(self)
	local name = "bigCubeOrange-"
	if self.on then
		name = name .. "on"
	else
		name = name .. "off"
	end
	return hash(name)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("interact") then
		self.on = not self.on
		msg.post("#sprite", "play_animation", { id = get_animation(self) })
	end
end